name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t docker_imagen_prueba .
      
    #- name: Build the Docker deplow a host
    #  run: docker run -d --name docker_contenedor_prueba -p 80:80 docker_imagen_prueba

  # ESTO ES MUCHO MUY IMPORTANTE!
    # Cuando se envien las credenciales usar los archivos
    # secretos de github y no agregar directamente aca.
  # ESTO ES MUCHO MUY IMPORTANTE!

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unittest tests
      run: python -m unittest discover -v
    
  coverall:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Install coverall
      run: pip install coveralls

    - name: Run unittest tests
      run: |
        coverage run --source=mypkg -m unittest tests/
        coveralls